version: "3"
services:
  api-gateway:
    build: "./api-gateway"
    depends_on:
      - users-service
      - listings-service
    ports:
      - 7000:7000
    volumes:
      - ./api-gateway:/opt/app

  listings-service:
    build: "./listings-service"
    depends_on:
      - listings-service-db
    environment:
      - DB_URI=mysql://root:password@listings-service-db/db?charset=UTF8
    ports:
      - 7100:7100
    volumes:
      - ./listings-service:/opt/app

  listings-service-db:
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
    image: mysql:5.7.20
    ports:
      - 0.0.0.0:7200:3306

  users-service:
    build: "./users-service"
    depends_on:
      - users-service-db
    environment:
      - DB_URI=mysql://root:password@users-service-db/db?charset=UTF8
    ports:
      - 7101:7101
    volumes:
      - ./users-service:/opt/app

  users-service-db:
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
    image: mysql:5.7.20
    ports:
      - 0.0.0.0:7201:3306

  movies-service:
    build: "./movies-service"
    depends_on:
      - movies-service-db
      - movies-service-db-seed
    environment:
      - DB_URI=mongodb://root:db:27017/?authSource=admin
      - DB_PORT=27017
      - DB_USER=root
      - DB_PASSWORD=db
      - DB_HOST=movies-service-db
      - DB_DATABASE=movies-service-db
    ports:
      - 7102:7102
    volumes:
      - ./movies-service:/opt/app

  movies-service-db:
    image: mongo:4.2.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: db
    ports:
      - 0.0.0.0:27017:27017
    command: mongod --auth

  movies-service-db-seed:
    image: fvilers/mongo-seed
    depends_on:
      - movies-service-db
    environment:
      - MONGO_HOST=movies-service-db
      - MONGO_PORT=27017
    volumes:
      - ./mongo-seed/data:/data
    command:
      [
        "mongoimport -u root -p db --host movies-service-db --port 27017 --authenticationDatabase admin --db movies-service-db --collection movies --mode upsert --type csv --file /data/movies.csv --headerline",
      ]
